import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";

import { Inter } from "next/font/google";
import "../globals.css";
import { CustomNavigationMenu } from "@/components/NavigationMenu";
import { Toaster } from "@/components/ui/toaster";
import { ReactElement } from "react";
import { SidebarDemo } from "@/components/SideBar";
import { setStaticParamsLocale } from "next-international/server";
import { BreadcrumbResponsive } from "@/components/CustomBreadCrumb";
import { ModeToggle } from "@/components/ui/mood-switcher";
import { AuthProvider } from "@/providers/auth-provider";
import { GuardsProvider } from "@/providers/guards-provider";
import UserAvatar from "@/components/UserAvatar";
import { ADMIN_AUTH_KEY, CLIENT_AUTH_KEY } from "@/constants";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({
  children,
  params: { locale },
}: {
  children: ReactElement;
  params: { locale: string };
}) {
  const cookieToken = cookies().get(ADMIN_AUTH_KEY)?.value;
  const clientCookieToken = cookies().get(CLIENT_AUTH_KEY)?.value;
  console.log(cookieToken, "cookieToken");
  return (
    <section>
      {/* <CustomNavigationMenu /> */}
      <SidebarDemo />
      <div className=" bg-primary-foreground h-20 flex items-center px-8   md:px-20  justify-between mb-4">
        <BreadcrumbResponsive />
        <div className="flex gap-4">
          <UserAvatar />
          <ModeToggle />
        </div>
      </div>
      <div className="px-8   md:px-20 ">
        {" "}
        <GuardsProvider cookieToken={cookieToken || clientCookieToken}>
          <> {children} </>
        </GuardsProvider>
      </div>
      <Toaster />
    </section>
  );
}
