import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";

import { Inter } from "next/font/google";
import "../globals.css";
import { CustomNavigationMenu } from "@/components/NavigationMenu";
import { Toaster } from "@/components/ui/toaster";
import { ReactElement } from "react";
import { SidebarDemo } from "@/components/SideBar";
import { setStaticParamsLocale } from "next-international/server";
import { BreadcrumbResponsive } from "@/components/CustomBreadCrumb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({
  children,
  params: { locale },
}: {
  children: ReactElement;
  params: { locale: string };
}) {
  return (
    <section>
      {/* <CustomNavigationMenu /> */}
      <SidebarDemo />
      <div className=" bg-primary-foreground h-20 flex items-center  mb-4">
        <BreadcrumbResponsive />
      </div>
      {children}
      <Toaster />
    </section>
  );
}
