import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";

import { Inter } from "next/font/google";
import "../globals.css";
import { CustomNavigationMenu } from "@/components/NavigationMenu";
import { Toaster } from "@/components/ui/toaster";
import { ReactElement } from "react";
import { headers } from "next/headers";
import { routesWithOutNaVbAR } from "@/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactElement }) {
  const headersList = headers();
  // read the custom x-url header
  const headerUrl = headersList.get("referer") || "";
  console.log(
    headerUrl,
    "headddddd",
    headersList.get("referer"),
    routesWithOutNaVbAR.some((route: string) => route.includes(headerUrl))
  );
  return (
    <html lang={"en"}>
      <body className={inter.className}>
        {routesWithOutNaVbAR.some((route: string) =>
          route.includes(headerUrl)
        ) && false}
        <CustomNavigationMenu />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
