import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";

import { Inter } from "next/font/google";
import "../globals.css";
import { CustomNavigationMenu } from "@/components/NavigationMenu";
import { Toaster } from "@/components/ui/toaster";
import { ReactElement } from "react";
import { cookies, headers } from "next/headers";
import {
  ADMIN_AUTH_KEY,
  CLIENT_AUTH_KEY,
  routesWithOutNaVbAR,
} from "@/constants";
import Footer from "@/components/Footer";
import { CartProvider } from "@/providers/cart-provider";
import { GuardsProvider } from "@/providers/guards-provider";
import PromoBanner from "@/components/PromoBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactElement }) {
  const headersList = headers();
  // read the custom x-url header
  const headerUrl = headersList.get("referer") || "";
  console.log(
    headerUrl,
    "headddddd",
    headersList.get("referer"),
    routesWithOutNaVbAR.some((route: string) => route.includes(headerUrl))
  );
  const cookieToken = cookies().get(ADMIN_AUTH_KEY)?.value;
  const clientCookieToken = cookies().get(CLIENT_AUTH_KEY)?.value;
  return (
    <section>
      <GuardsProvider cookieToken={cookieToken || clientCookieToken}>
        <CartProvider>
          <>
            <CustomNavigationMenu />
            <br />
            <br />
            <br />

            <PromoBanner />

            {children}
            <Toaster />
            <Footer />
          </>
        </CartProvider>
      </GuardsProvider>
    </section>
  );
}
